version: '3.8'

services:
  auth-provider-server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  
  auth-provider-db:
    image: mysql:8.0
    container_name: auth-provider-db
    restart: always
    environment:
      MYSQL_DATABASE: auth-provider-db
      MYSQL_USER: auth-provider-db-dev
      MYSQL_PASSWORD: ${AUTH_PROVIDER_DB_PASS}
    ports:
      - "5342:5342" # Maps host port 3306 to container port 3306
    volumes:
      - mysql_dev_data:/var/lib/mysql


volumes:
  mysql_dev_data:
